export const GET_ANIMES = 'GET_ANIMES';
export const CLEAN_GET_ANIMES = 'CLEAN_GET_ANIMES';
export const SET_IS_FINISHED = 'SET_IS_FINISHED';
export const SEARCH_ANIME = 'SEARCH_ANIME';
export const CLEAN_ANIME_SEARCH = 'CLEAN_ANIME_SEARCH';
export const GET_ANIME_INFO = 'GET_ANIME_INFO';
export const CLEAN_ANIME_INFO = 'CLEAN_ANIME_INFO';
export const GET_TOP_ANIMES_GENERAL = 'GET_TOP_ANIMES_GENERAL';
export const CLEAN_TOP_ANIMES_GENERAL = 'CLEAN_TOP_ANIMES_GENERAL';
export const GET_TOP_ANIMES = 'GET_TOP_ANIMES';
export const CLEAN_TOP_ANIMES = 'CLEAN_TOP_ANIMES';
export const GET_BROWSED_ANIMES = 'GET_BROWSED_ANIMES';
export const CLEAN_BROWSED_ANIMES = 'CLEAN_BROWSED_ANIMES';

export const SIGN_IN = 'SIGN_IN';
export const ERROR_SIGN_IN = 'ERROR_SIGN_IN';
export const SIGN_OUT ='SIGN_OUT';
export const SIGN_UP = 'SIGN_UP';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_ERROR = 'SET_CURRENT_USER_ERROR';
export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAN_MESSAGE = 'CLEAN_MESSAGE';

export const GET_ANIME_FL = 'GET_ANIME_FL';
export const GET_ANIME_FL_ERROR = 'GET_ANIME_FL_ERROR';
export const CLEAN_GET_ANIME_FL = 'CLEAN_GET_ANIME_FL';
export const REMOVE_ANIME = 'REMOVE_ANIME';

export const GET_USER_ANIME_LIST = 'GET_USER_ANIME_LIST';
export const CLEAN_USER_ANIME_LIST = 'CLEAN_USER_ANIME_LIST';